### PR TITLE
Introduce automatic CI for gpg sigs and gitian verification

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Pls see 171b00596869de64f8ee098b22654a4b7a6a70c3

**Comment by PastaPastaPasta** [comment]
done

**Review by UdjinM6 — APPROVED** [review]
Seems to be working as expected when applied to my own repo (https://github.com/UdjinM6/gitian.sigs/tree/pr121 + https://github.com/UdjinM6/gitian.sigs/pull/1)

ACK

**Review by xdustinface — APPROVED** [review]
utACK

**Pull request merged**
