### PR TITLE
Add 18.0.0-rc6 sigs for knst

### PR DESCRIPTION
**Pull request by knst**

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Your hashes do not match... Try dropping ~/gitian-builder/inputs/ folder and run builder again.

**Comment by knst** [comment]
```
$ git diff ./18.0.0-rc6-linux/knst/dash-linux-18-build.assert ./18.0.0-rc6-linux/UdjinM6/dash-linux-18-build.assert && echo SAME
SAME
```

Should be OK now (was different)

**Comment by PastaPastaPasta** [comment]
They do now it seems :)

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
Looks good now 👍 

ACK

**Pull request merged**
