### PR TITLE
Add 0.16.0.0 sigs for thephez

### PR DESCRIPTION
**Pull request by thephez**
In case you want some more (I figured it out @PastaPastaPasta :slightly_smiling_face:)

### CODE REVIEW

**Review by UdjinM6 — COMMENTED** [review]
Looks good :)

Might be a good idea to add your pgp pubkey to https://github.com/dashpay/dash/tree/develop/contrib/gitian-keys/

**Comment by PastaPastaPasta** [comment]
For @thephez I think this probably makes sense, but normally, people should do builds a time or two before adding key

**Comment by thephez** [comment]
> For @thephez I think this probably makes sense, but normally, people should do builds a time or two before adding key

Yes, I think this makes sense :+1:

**Review by xdustinface — DISMISSED** [review]
ACK

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by PastaPastaPasta — APPROVED** [review]
ACK, gitian-build.py --verify is happy :+1:

**Review by PastaPastaPasta — CHANGES_REQUESTED** [review]
Gotta redo signed sigs

**Comment by thephez** [comment]
@PastaPastaPasta Should be good now

**Review by PastaPastaPasta — APPROVED** [review]
ACK

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by xdustinface — APPROVED** [review]
ACK

**Pull request merged**
