### PR TITLE
Add 0.16.0.1 signatures for thephez

### PR DESCRIPTION
**Pull request by thephez**
gitian-build.py -v seemed happy :+1:

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
ACK `python3 dash/contrib/gitian-build.py -v pasta 0.16.0.0` is happy

**Review by UdjinM6 — APPROVED** [review]
ACK

**Comment by UdjinM6** [comment]
@PastaPastaPasta it should be `0.16.0.1` btw ;)

**Review by xdustinface — APPROVED** [review]
ACK

**Pull request merged**
