### PR TITLE
Add 0.16.0.1 sigs for UdjinM6

### PR DESCRIPTION
**Pull request by UdjinM6**

### CODE REVIEW

**Review by xdustinface — APPROVED** [review]
ACK

**Comment by nmarley** [comment]
post-merge ACK, verified sigs and hashes

@UdjinM6 `gpg` keeps telling me your key has expired, is there something I need to do to pull an updated version?

**Comment by UdjinM6** [comment]
@nmarley hmm... `gpg --refresh-keys 83592BD1400D58D9`?

**Comment by nmarley** [comment]
That did it, thanks!

**Pull request merged**
