### PR TITLE
Add 0.16.0.0 sigs for pasta

### PR DESCRIPTION
**Pull request by PastaPastaPasta**

### CODE REVIEW

**Review by UdjinM6 — COMMENTED** [review]
Looks good so far

**Review by xdustinface — DISMISSED** [review]
ACK

**Review by UdjinM6 — DISMISSED** [review]
ACK

**Comment by xdustinface** [comment]
sure? :D

**Review by UdjinM6 — APPROVED** [review]
ACK

**Review by xdustinface — APPROVED** [review]
ACK

**Pull request merged**
